# ============================================================
# zensical.toml (Zensical configuration file)
# ============================================================

[project]
site_name = "Automation Project"
site_url = "https://Justice-netizen.github.io/Automation-"
repo_url = "https://github.com/Justice-netizen/Automation-"
repo_name = "Justice-netizen/Automation-"
site_description = "Project documentation"
docs_dir = "docs"
site_dir = "site"
edit_uri = "edit/main/docs/"

[project.extra]
social = [
    {icon = "fontawesome/brands/github", link = "https://github.com/Justice-netizen/Automation-" },
]

[project.plugins.search]
lang = "en"

[project.plugins.mkdocstrings.handlers.python]
paths = ["src"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
show_source = true
show_root_heading = true
show_root_toc_entry = true
show_signature_annotations = true
separate_signature = true

[project.theme]
features = [
    "navigation.tracking",
    "navigation.expand",
    "navigation.path",
    "navigation.prune",
    "navigation.indexes",
    "toc.follow",
    "toc.integrate",
    "navigation.top",
]

nav = [
    { "Home" = "index.md" },
    { "Project Instructions" = "project-instructions.md" },
    { "Your Files" = "your-files.md" },
    { "Glossary" = "glossary.md" },
    { "Module" = "module/index.md" },
    { "Branching" = "module/branching.md" },
    { "Functions" = "module/functions.md" },
    { "Operators" = "module/operators.md" },
    { "Repetition" = "module/repetition.md" },
]
